---
name: "prsco3_grad"
backend: jax

# raw data source
raw_data:
  type: empad
  path: "~/lebeau_shared/experimental_prsco3/PSO.json"

# initialization

post_init:
 - drop_nans
 - diffraction_align

slices:
  n: 21
  total_thickness: 210

engines:
 - type: 'gradient'
   sim_shape: [128, 128]
   probe_modes: 8
   niter: 200
   grouping: 16
   bwlim_frac: 1.0

   noise_model:
     type: "amplitude"
     gaussian_variance: 0.1
     eps: 0.03324637658131251
     offset: 0.0

   solvers:
     object:
       type: 'adam'
       learning_rate: 0.004
       nesterov: True
     probe:
       type: 'adam'
       learning_rate: 0.01
       nesterov: True
     positions:
       type: 'sgd'
       learning_rate: 0.3
       momentum: 0.30
       nesterov: True

   regularizers:
     - type: obj_l2
       cost: 0.01
     - type: obj_l2
       cost: 0.01

   group_constraints: []
   iter_constraints:
     - type: limit_probe_support
       max_angle: 23.0
     - type: clamp_object_amplitude
       amplitude: 1.0
     - type: obj_gaussian
       sigma: 0.05
       weight: 1.0
     - type: layers
       sigma: 200
       weight: 0.1

   update_probe: {after: 2}
   update_positions: {after: 5}

   save: {every: 10}
   save_images: {every: 5}
   save_options:
     images: [
      'probe', 'probe_recip', 'object_phase_sum', 'object_mag_sum',
      'object_phase_stack', 'object_mag_stack'
     ]
